import { createCipheriv, createHash, pbkdf2Sync, randomBytes } from 'crypto'
import { readFileSync, writeFileSync } from 'fs'

const PASSPHRASE = 'o7pV@ult_2024!secure#'
const ALGO = 'aes-256-gcm'
const KEY_LEN = 32
const SALT = randomBytes(32)
const KEY = pbkdf2Sync(PASSPHRASE, SALT, 600000, KEY_LEN, 'sha512')

const connStr = process.env.DATABASE_URL || readFileSync(0, 'utf-8').trim()
if (!connStr) {
  console.error('Usage: set DATABASE_URL env var or pipe connection string to stdin')
  process.exit(1)
}

const iv = randomBytes(16)
const cipher = createCipheriv(ALGO, KEY, iv)
let encrypted = cipher.update(connStr, 'utf-8', 'hex')
encrypted += cipher.final('hex')
const authTag = cipher.getAuthTag().toString('hex')

const output = `// Auto-generated by encrypt-connstr.js - DO NOT EDIT MANUALLY
export const ENCRYPTED_CONNSTR = '${encrypted}'
export const IV = '${iv.toString('hex')}'
export const AUTH_TAG = '${authTag}'
export const SALT = '${SALT.toString('hex')}'
`

writeFileSync('src/lib/connstr.ts', output)
console.log('Encrypted connection string written to src/lib/connstr.ts')
